function [SubjectID, Age, Gender, Weight, Day1, Day2, Day3] = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  [SUBJECTID, AGE, GENDER, WEIGHT, DAY1, DAY2, DAY3] =
%  IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as column vectors.
%
%  [SUBJECTID, AGE, GENDER, WEIGHT, DAY1, DAY2, DAY3] =
%  IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  [SubjectID, Age, Gender, Weight, Day1, Day2, Day3] = importfile1("/Users/rjhorn/Documents/DocumentsCopiedFromiCloud/GitHub/RileyHornAssignments/assignment5/isok_data_6803.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 27-Oct-2019 09:29:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["SubjectID", "Age", "Gender", "Weight", "Day1", "Day2", "Day3"];
opts.VariableTypes = ["string", "double", "categorical", "double", "double", "double", "double"];
opts = setvaropts(opts, 1, "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 3], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
SubjectID = tbl.SubjectID;
Age = tbl.Age;
Gender = tbl.Gender;
Weight = tbl.Weight;
Day1 = tbl.Day1;
Day2 = tbl.Day2;
Day3 = tbl.Day3;
end